# Generated by Django 5.2.6 on 2025-09-04 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_conn', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.base')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
            bases=('hub.base',),
        ),
    ]
